export interface CountryData {
  code: string;
  name: string;
  flag: string;
  regions: string[];
}

export const WEST_AFRICA_COUNTRIES: CountryData[] = [
  {
    code: "GN",
    name: "Guinée",
    flag: "🇬🇳",
    regions: [
      "Conakry",
      "Conakry - Kaloum",
      "Conakry - Dixinn",
      "Conakry - Matam",
      "Conakry - Ratoma",
      "Conakry - Matoto",
      "Conakry - Port Autonome",
      "Kassa (Îles de Loos)",

      // Region Kindia & Prefectures / Sub-prefectures
      "Coyah",
      "Coyah - Maneah",
      "Coyah - Kouriah",
      "Dubréka",
      "Dubréka - Khorira",
      "Dubréka - Tanéné",
      "Forécariah",
      "Forécariah - Farmoriah (Frontière 🇸🇱)",
      "Forécariah - Maferinya",
      "Kindia",
      "Kindia - Friguiagbé",
      "Kindia - Bangouya",
      "Kindia - Damakania",
      "Télimélé",
      "Télimélé - Gougoudjé",

      // Region Boké & Prefectures / Sub-prefectures
      "Boké",
      "Boké - Kamsar (Port Minier)",
      "Boké - Sangarédi (Bauxite)",
      "Boké - Kolaboui",
      "Boffa",
      "Boffa - Koba",
      "Boffa - Tamita",
      "Fria",
      "Fria - Kimbo (Alumine)",
      "Gaoual",
      "Gaoual - Kounsitel (Gisement d'or)",
      "Koundara",
      "Koundara - Sambaïlo (Frontière 🇸🇳)",
      "Koundara - Sareboïdo",

      // Region Mamou & Prefectures / Sub-prefectures
      "Mamou",
      "Mamou - Timbo",
      "Mamou - Bouliwel",
      "Mamou - Dounet",
      "Dalaba",
      "Dalaba - Ditinn",
      "Pita",
      "Pita - Timbi-Madina (Pomme de terre)",
      "Pita - Sintali",

      // Region Labé & Prefectures / Sub-prefectures
      "Labé",
      "Labé - Popodara",
      "Labé - Hafia",
      "Mali",
      "Mali - Yembering",
      "Mali - Balaki (Frontière 🇸🇳)",
      "Lélouma",
      "Lélouma - Sagalé",
      "Koubia",
      "Tougué",

      // Region Faranah & Prefectures / Sub-prefectures
      "Faranah",
      "Faranah - Tiro",
      "Faranah - Banian",
      "Dabola",
      "Dabola - Bissikrima",
      "Dinguiraye",
      "Dinguiraye - Banora",
      "Kissidougou",
      "Kissidougou - Yendé",
      "Kissidougou - Bardou",

      // Region Kankan & Prefectures / Sub-prefectures
      "Kankan",
      "Kankan - Karifamoriah",
      "Kankan - Batè-Nafadji",
      "Siguiri",
      "Siguiri - Kintinian (Mine SAG)",
      "Siguiri - Bouré",
      "Siguiri - Doko",
      "Siguiri - Malea",
      "Mandiana",
      "Mandiana - Dialakoro",
      "Kouroussa",
      "Kouroussa - Cissela",
      "Kérouané",
      "Kérouané - Banankoro (Diamant)",
      "Simandou 2040 - Zone Minière Block 1&2",
      "Simandou 2040 - Zone Minière Block 3&4",

      // Region Nzérékoré (Guinée Forestière) & Prefectures / Sub-prefectures
      "Nzérékoré",
      "Nzérékoré - Gouécké",
      "Nzérékoré - Yalenzou",
      "Macenta",
      "Macenta - Kouankan",
      "Macenta - Sérédou",
      "Guéckédou",
      "Guéckédou - N'Zboo",
      "Guéckédou - Tekoulo",
      "Lola",
      "Lola - Bossou",
      "Lola - N'Zoo (Frontière 🇨🇮)",
      "Beyla",
      "Beyla - Boola",
      "Yomou",
      "Yomou - Diécké (Frontière 🇱🇷)",
    ],
  },
  {
    code: "SN",
    name: "Sénégal",
    flag: "🇸🇳",
    regions: [
      "Dakar (Capitale)",
      "Dakar - Port Autonome / Zone Industrielle",
      "Thiès",
      "Mbour / Saly",
      "Kaolack",
      "Saint-Louis",
      "Ziguinchor (Casamance)",
      "Diourbel / Touba",
      "Louga",
      "Tambacounda",
      "Kolda",
      "Kédougou",
      "Fatick",
      "Kaffrine",
      "Matam",
      "Rosso (Frontière 🇲🇷)",
      "Kidira (Frontière 🇲🇱)",
    ],
  },
  {
    code: "ML",
    name: "Mali",
    flag: "🇲🇱",
    regions: [
      "Bamako (Capitale)",
      "Bamako - Zone Industrielle",
      "Kayes (Axe Guinée/Sénégal)",
      "Sikasso (Axe Côte d'Ivoire)",
      "Ségou",
      "Mopti",
      "Koulikoro",
      "Koutiala",
      "San",
      "Kita",
      "Gao",
      "Tombouctou",
    ],
  },
  {
    code: "CI",
    name: "Côte d'Ivoire",
    flag: "🇨🇮",
    regions: [
      "Abidjan - Port Autonome / Zone Franche",
      "Abidjan - Yopougon / Koumassi",
      "Bouaké",
      "San-Pédro (Port Minier / Cacao)",
      "Yamoussoukro (Capitale)",
      "Korhogo",
      "Daloa",
      "Man",
      "Gagnoa",
      "Odienné (Frontière Guinée)",
      "Ferkessédougou",
      "Boundiali",
    ],
  },
  {
    code: "SL",
    name: "Sierra Leone",
    flag: "🇸🇱",
    regions: [
      "Freetown (Capital / Port)",
      "Freetown - Wellington Industrial",
      "Bo",
      "Kenema",
      "Makeni",
      "Koidu (Diamond Zone)",
      "Lungi (Airport)",
      "Gbalamuya / Pamelap (Frontière Guinée)",
      "Kamakwie",
      "Kabala",
    ],
  },
  {
    code: "LR",
    name: "Liberia",
    flag: "🇱🇷",
    regions: [
      "Monrovia (Capital / Port)",
      "Gbarnga",
      "Buchanan (Port)",
      "Kakata",
      "Ganta (Frontière Guinée)",
      "Harper",
      "Voinjama",
      "Zwedru",
    ],
  },
  {
    code: "GW",
    name: "Guinée-Bissau",
    flag: "🇬🇼",
    regions: [
      "Bissau (Capitale / Port)",
      "Bafatá",
      "Gabú (Frontière Guinée)",
      "Cacheu",
      "Quinhamel",
      "Farim",
    ],
  },
  {
    code: "GH",
    name: "Ghana",
    flag: "🇬🇭",
    regions: [
      "Accra (Capital)",
      "Tema (Port / Industrial)",
      "Kumasi",
      "Tamale",
      "Sekondi-Takoradi",
      "Cape Coast",
      "Aflao (Frontière Togo)",
    ],
  },
  {
    code: "BF",
    name: "Burkina Faso",
    flag: "🇧🇫",
    regions: [
      "Ouagadougou (Capitale)",
      "Bobo-Dioulasso",
      "Koudougou",
      "Banfora",
      "Dédougou",
    ],
  },
  {
    code: "TG",
    name: "Togo",
    flag: "🇹🇬",
    regions: [
      "Lomé (Capitale / Port Autonome)",
      "Sokodé",
      "Kara",
      "Kpalimé",
      "Atakpamé",
      "Dapaong",
    ],
  },
  {
    code: "BJ",
    name: "Bénin",
    flag: "🇧🇯",
    regions: [
      "Cotonou (Port Autonome)",
      "Porto-Novo (Capitale)",
      "Parakou",
      "Djougou",
      "Bohicon",
      "Kandi",
    ],
  },
  {
    code: "NG",
    name: "Nigeria",
    flag: "🇳🇬",
    regions: [
      "Lagos - Apapa Port / Lekki Free Zone",
      "Abuja (Capital)",
      "Kano",
      "Ibadan",
      "Port Harcourt",
    ],
  },
];
